macroarea: sonno_ritmi
version: 1.0

map:
  # ===== ORARI E ROUTINE =====
  orari_sonno_e_pasti[]:
    feature: orari_sonno_e_pasti
    values:
      orari_regolari: orari_regolari
      cerco_routine: cerco_routine
      orari_variano: orari_variano
      ritmo_irregolare: ritmo_irregolare

  ritmocircadiano[]:
    feature: ritmocircadiano
    values:
      molto_regolare: molto_regolare
      moderatamente_regolare: moderatamente_regolare
      variabile: variabile
      molto_irregolare: molto_irregolare
      non_so: non_so
  note_ritmocircadiano:
    feature: note_ritmocircadiano
    passthrough: true

  ora_letto:
    feature: ora_letto
    passthrough: true

  ora_sveglia:
    feature: ora_sveglia
    passthrough: true

  tempo_addormentamento:
    feature: tempo_addormentamento
    passthrough: true

  ore_effettive_sonno:
    feature: ore_effettive_sonno
    passthrough: true

  ore_sonno[]:
    feature: ore_sonno
    values:
      meno_5: meno_5
      5_6: 5_6
      6_7: 6_7
      7_8: 7_8
      piu_9: piu_9
      non_so: non_so

  # ===== QUALITÃ€ E DISTURBI =====
  qualita_sonno[]:
    feature: qualita_sonno
    values:
      ottima: ottima
      buona: buona
      discreta: discreta
      scarsa: scarsa

  qualita_del_sonno[]:
    feature: qualita_del_sonno
    values:
      molto_buona: molto_buona
      abbastanza_buona: abbastanza_buona
      abbastanza_cattiva: abbastanza_cattiva
      cattiva: cattiva

  # --- Sintomi specifici ---
  non_addormentarsi_entro_30_minuti[]:
    feature: non_addormentarsi_entro_30_minuti
    values:
      mai: mai
      raramente: raramente
      1_2: 1_2
      3_plus: 3_plus

  sveglia_nella_notte[]:
    feature: sveglia_nella_notte
    values:
      mai: mai
      raramente: raramente
      1_2: 1_2
      3_plus: 3_plus

  svegliarsi_per_andare_in_bagno[]:
    feature: svegliarsi_per_andare_in_bagno
    values:
      mai: mai
      raramente: raramente
      1_2: 1_2
      3_plus: 3_plus

  non_respirare_bene_di_notte[]:
    feature: non_respirare_bene_di_notte
    values:
      mai: mai
      raramente: raramente
      1_2: 1_2
      3_plus: 3_plus

  tosse_e_russare[]:
    feature: tosse_e_russare
    values:
      mai: mai
      raramente: raramente
      1_2: 1_2
      3_plus: 3_plus

  freddo_di_notte[]:
    feature: freddo_di_notte
    values:
      mai: mai
      raramente: raramente
      1_2: 1_2
      3_plus: 3_plus

  caldo_la_notte[]:
    feature: caldo_la_notte
    values:
      mai: mai
      raramente: raramente
      1_2: 1_2
      3_plus: 3_plus

  brutti_sogni[]:
    feature: brutti_sogni
    values:
      mai: mai
      raramente: raramente
      1_2: 1_2
      3_plus: 3_plus

  dolori_la_notte[]:
    feature: dolori_la_notte
    values:
      mai: mai
      raramente: raramente
      1_2: 1_2
      3_plus: 3_plus

  altri_problemi_che_disturbano_sonno:
    feature: altri_problemi_che_disturbano_sonno
    passthrough: true

  altri_problemi_che_disturbano_sonno_frequenza[]:
    feature: altri_problemi_che_disturbano_sonno_frequenza
    values:
      meno_1: meno_1
      1_2: 1_2
      3_plus: 3_plus

  # ===== SINTOMI DIURNI E DIAGNOSI =====
  difficolta_a_rimanere_sveglio[]:
    feature: difficolta_a_rimanere_sveglio
    values:
      mai: mai
      poche_volte: poche_volte
      spesso: spesso
      ogni_giorno: ogni_giorno

  energie_insufficienti[]:
    feature: energie_insufficienti
    values:
      mai: mai
      poche_volte: poche_volte
      spesso: spesso
      ogni_giorno: ogni_giorno

  sudorazione_notturna[]:
    feature: sudorazione_notturna
    values:
      mai: mai
      raro: raro
      frequente: frequente
      solo_stress: solo_stress
      non_so: non_so
  note_sudorazione_notturna:
    feature: note_sudorazione_notturna
    passthrough: true

  disturbi_del_sonno_diagnosticati[]:
    feature: disturbi_del_sonno_diagnosticati
    values:
      si: si
      no: no

  # ===== FARMACI =====
  assunzione_farmaci_sonno[]:
    feature: assunzione_farmaci_sonno
    values:
      mai: mai
      occasionale: occasionale
      frequente: frequente
      uso_continuativo: uso_continuativo

  tipologia_farmaci_sonno:
    feature: tipologia_farmaci_sonno
    passthrough: true

  assunzione_attuale_farmaci_sonno:
    feature: assunzione_attuale_farmaci_sonno
    values:
      si: si
      no: no

  durata_assunzione_farmaci_sonno:
    feature: durata_assunzione_farmaci_sonno
    passthrough: true