HER001 : "Malattia coronarica cronica"
HER002 : "Ipertensione essenziale"
HER003 : "Dislipidemia"
HER004 : "Sindrome metabolica"
HER005 : "Diabete mellito tipo 2"
HER006 : "Trombofilia ereditaria"
HER007 : "Ictus giovanile"
HER008 : "Aborti ricorrenti (trombofilia)"
HER009 : "Complicanze ostetriche (trombofilia)"
HER010 : "Alzheimer familiare precoce"
HER011 : "Demenza (Alzheimer, vascolare)"
HER012 : "Declino cognitivo lieve"
HER013 : "Tumore mammario ereditario (BRCA1/2)"
HER014 : "Tumore ovarico ereditario"
HER015 : "Tumore endometriale"
HER016 : "Tumore prostatico"
HER017 : "Tumore colorettale"
HER018 : "Sindrome di Lynch"
HER019 : "Poliposi adenomatosa familiare"
HER020 : "Depressione maggiore ricorrente"
HER021 : "Lupus eritematoso sistemico"
HER022 : "Psoriasi"
HER023 : "Malattie infiammatorie intestinali"
HER024 : "Cardiopatia ereditaria"
HER025 : "Morte cardiaca improvvisa in giovane età"
HER026 : "Eventi trombotici in sedi inusuali"
HER027 : "Cardiopatie (rischio aumenta con l’età)"
HER028 : "Ictus e TIA"
#HER029 : "Diabete tipo 2"
HER030 : "Tumore polmone"
HER031 : "Osteoporosi/fratture da fragilità"
HER032 : "Malattie neurodegenerative (es. Parkinson)"
HER033 : "Malattie cardiovascolari (esordio precoce più frequente negli uomini, ma maggiore mortalità nelle donne dopo la menopausa)"
HER034 : "Depressione (più prevalente nelle donne)"
HER035 : "Disturbo da abuso di sostanze"
HER036 : "Anemia falciforme"
HER037 : "Talasemia"
HER038 : "Ipensensibilità a farmaci (HLA-B1502/carbamazepina)"
HER039 : "Ipovitaminosi D/osteomalacia"
HER040 : "Disturbo post-traumatico da stress (PTSD)"
HER041 : "Depressione maggiore"
HER042 : "Disturbi d’ansia e panico"
HER043 : "Disturbi psicosomatici (colon irritabile, fibromialgia)"
HER044 : "Rischio suicidario aumentato"
HER045 : "Malattie cardiovascolari da stress cronico (sindrome di Takotsubo)"
HER046 : "Dismetabolismi (obesità, sindrome metabolica)"
HER047 : "Disfunzioni del sonno"
HER048 : "Compromissione immunitaria da stress cronico"
HER049 : "Artrite Reumatoide (AR)"
HER050 : "Tiroidite di Hashimoto (autoimmune)"
HER051 : "Tumori solidi (es. ovarico, colon-retto, prostata)"
HER052 : "Morbo di Addison autoimmune (insufficienza surrenalica primaria)"
HER053 : "Ictus ischemico acuto"
HER054 : "Depressione maggiore e sintomi da ansia grave"
HER055 : "Stress cronico con disregolazione dell’asse HPA"
HER056 : "Tumore epatico (epatocarcinoma)"
HER057 : "Disidratazione grave"
HER058 : "Prediabete"
HER059 : "Steatosi epatica non alcolica (NAFLD)"
HER060 : "Sindrome da attivazione macrofagica"
HER061 : "Pubertà precoce o ritardata"
HER062 : "Obesità cronica"
HER063 : "Iperplasia surrenalica congenita"
HER064 : "Ipogonadismo"
HER065 : "Infezioni croniche"
HER066 : "Anemia da infiammazione"
HER067 : "Colon irritabile post-infettivo"
HER068 : "Infertilità"
HER069 : "Ipoglicemia reattiva"
HER070 : "Trombocitopenia"
HER071 : "Trombocitosi"
HER072 : "Iperpotassiemia / Ipopotassiemia"
HER073 : "Nefropatia diabetica"
HER074 : "Ittero"
HER075 : "Ipertrigliceridemia"
HER076 : "Pancreatite cronica / Tumore pancreatico"
HER077 : "Iperinsulinemia"
HER078 : "Tiroidite subacuta/cronica"
HER079 : "Infezioni batteriche e virali acute o croniche"
HER080 : "Disfunzioni mitocondriali"
HER081 : "Colestasi"
HER082 : "Infezioni opportunistiche"
HER083 : "Glomerulonefrite"
HER084 : "Leucemia acuta e cronica"
HER085 : "Disturbi dell’umore e neuropsichiatrici"
HER086 : "Sindrome di Cushing"
HER087 : "Anemia (sideropenica, megaloblastica, emolitica)"
HER088 : "Ipertiroidismo"
HER089 : "Linfoma"
HER090 : "Disturbi cognitivi/dell’umore"
HER091 : "Acidosi metabolica"
HER092 : "Epatite"
HER093 : "Cancro"
HER094 : "Sindrome intestino irritabile"
HER095 : "Malattie metaboliche rare"
HER096 : "Mielodisplasie/mielofibrosi"
HER097 : "Infiammazioni sistemiche/localizzate"
HER098 : "Insufficienza renale"
HER099 : "Menopausa precoce"
HER100 : "Xantomatosi"
HER101 : "Malassorbimento/intolleranze"
HER102 : "Amenorrea/irregolarità mestruali"
HER103 : "Sindrome Nefrosica"
HER104 : "Deficit Vitamina A"
HER105 : "Deficit Vitamina B1 (Tiamina)"
HER106 : "Deficit Vitamina B2 (Riboflavina)"
HER107 : "Deficit Vitamina B3 (Niacina)"
HER108 : "Deficit Vitamina B6"
HER109 : "Deficit Vitamina B12"
HER110 : "Deficit Folati"
HER111 : "Deficit Vitamina C"
HER112 : "Deficit Vitamina E"
HER113 : "Deficit Vitamina K"
HER114 : "Disbiosi intestinale"
HER115 : "Chetoacidosi diabetica (DKA)"
HER116 : "Ipotiroidismo"
HER117 : "Insulino-resistenza"
HER118 : "Iperazotemia prerenale/postrenale"
HER119 : "Tiroidite subacuta (De Quervain)"
HER120 : "Cirrosi epatica"
HER121 : "Diabete tipo 1"
HER122 : "Sindrome di Gilbert"
HER123 : "ME/CFS (Sindrome da fatica cronica)"
HER124 : "Aterosclerosi subclinica"
HER125 : "Tumori ipofisari (PitNET)"
HER126 : "Ipercolesterolemia familiare"
HER127 : "Gozzo tossico multinodulare"
HER128 : "Adenoma tossico"
HER129 : "Tachicardia sinusale"
HER130 : "Bradicardia sinusale"
HER131 : "Fibrillazione atriale"
HER132 : "Extrasistolia ventricolare/sopraventricolare"
HER133 : "Sindrome QT lungo/corto"
HER134 : "POTS (Sindrome tachicardia posturale ortostatica)"
HER135 : "Sindrome nodo seno/blocco AV"
HER136 : "Shock cardiogeno"
HER137 : "Sepsi"
HER138 : "Ipotermia grave"
HER139 : "Ipertensione arteriosa primaria/secondaria"
HER140 : "Crisi ipertensive (urgenza/emergenza)"
HER141 : "Ipotensione ortostatica"
HER142 : "Shock ipovolemico/settico"
HER143 : "Feocromocitoma (crisi ipertensive episodiche)"
HER144 : "Insufficienza renale cronica (ipertensione)"
HER145 : "Disfunzione autonomica (es. Parkinson)"
HER146 : "Febbre da infezione acuta"
HER147 : "Sepsi/shock settico"
HER148 : "Covid-19/infezioni respiratorie"
HER149 : "Influenza"
HER150 : "Polmonite"
HER151 : "Infezioni urinarie"
HER152 : "Meningite/encefalite"
HER153 : "Febbre reumatica/febbre mediterranea familiare"
HER154 : "Malaria/dengue/malattie tropicali"
HER155 : "Ipotermia accidentale/indotta"
HER156 : "Tireotossicosi (temperatura elevata)"
HER157 : "Colpo di calore"
HER158 : "Neoplasie con febbre neoplastica"
HER159 : "Malattie autoimmuni con febbre (lupus, vasculiti)"
HER160 : "BPCO"
HER161 : "Polmonite / insufficienza respiratoria"
HER162 : "Embolia polmonare"
HER163 : "ARDS"
HER164 : "Ansia / iperventilazione psicogena"
HER165 : "Acidosi metabolica compensata (respiro di Kussmaul)"
HER166 : "Sepsi grave"
HER167 : "Insufficienza cardiaca congestizia (respiro di Cheyne-Stokes)"
HER168 : "Insufficienza respiratoria acuta o cronica"
HER169 : "Polmonite grave/COVID-19 severo"
HER170 : "Enfisema"
HER171 : "Fibrosi polmonare"
HER172 : "Malattie interstiziali"
HER173 : "OSAS (apnee ostruttive sonno)"
HER174 : "Sindrome da ipoventilazione obesità-correlata"
HER175 : "Ipossia in alta quota"
HER176 : "Emoglobina patologica (metaemoglobinemia, carbossiemoglobinemia)"
HER177 : "Shunt cardiaci congeniti (ipotossiemia persistente)"
HER178 : "Embolia polmonare massiva"
HER179 : "Morte cardiaca improvvisa"
HER180 : "Neuropatia autonomica diabetica"
HER181 : "Scompenso cardiaco congestizio"
HER182 : "Sindrome post-COVID (long COVID)"
HER183 : "Burnout cronico"
HER184 : "Disautonomia"
HER185 : "Overtraining in atleti"
HER186 : "Fluttuazioni glicemiche (CGM)"
HER187 : "Sindrome vasovagale / sincopi neurocardiogene"
HER188 : "Attacchi di panico con manifestazioni vegetative"
HER189 : "Monitoraggio post-operatorio in pazienti fragili"
HER190 : "Gastrite funzionale / Dismotilità"
HER191 : "Malattia da reflusso gastroesofageo (GERD)"
HER192 : "Disturbi del comportamento alimentare (DCA)"
HER193 : "Iperuricemia e gotta"
HER194 : "Osteoartrosi"
HER195 : "Neuropatie periferiche nutrizionali (carenza B/E)"
HER196 : "Carenza di zinco"
HER197 : "Carenza di magnesio"
HER198 : "Anafilassi"
HER199 : "Orticaria / Angioedema"
HER200 : "Asma allergica"
HER201 : "Dermatite atopica"
HER202 : "Sindrome orale allergica"
HER203 : "Celiachia"
HER204 : "Sensibilità al glutine non celiaca (NCGS)"
HER205 : "Intolleranza all'istamina"
HER206 : "Calcoli renali (Nefrolitiasi)"
HER207 : "Rabdomiolisi / Crampi muscolari severi"
HER208 : "Ipernatriemia / Iponatriemia"
HER209 : "Stipsi cronica"
HER210 : "Delirium / Stato confusionale acuto"
HER211 : "Squilibri del calcio (Ipocalcemia / Ipercalcemia)"
HER212 : "Sindrome da inappropriata secrezione di ADH (SIADH)"
HER213 : "Carcinoma mammario (non ereditario/post-menopausa)"
HER214 : "Carcinoma gastrico"
HER215 : "Tumore esofageo"
HER216 : "Diverticolosi / Diverticolite"
HER217 : "Permeabilità intestinale aumentata (Leaky Gut)"
HER218 : "Morbo di Crohn"
HER219 : "Colite ulcerosa"
HER220 : "Eccessiva sonnolenza diurna (EDS)"
HER221 : "Disturbo da movimenti periodici degli arti (PLMD)"
HER222 : "Insonnia cronica / Insonnia secondaria"
HER223 : "Narcolessia / Disregolazione orexina"
HER224 : "Disturbo da lavoro a turni (Shift Work Disorder)"
HER225 : "Jet Lag / Jet Lag Sociale"
HER226 : "Disturbi del ritmo circadiano (Fase avanzata/ritardata)"
HER227 : "Ipertensione notturna (Non-dipping)"
HER228 : "Cefalea cronica / Emicrania"
HER229 : "Epilessia notturna"
HER230 : "Disturbo bipolare"
HER231 : "Schizofrenia"
HER232 : "Sindrome da deprivazione di sonno cronica"
HER233 : "Insonnia paradossa (Sleep misperception)"