HER001 : "Malattia coronarica cronica"
HER002 : "Ipertensione essenziale"
HER003 : "Dislipidemia"
HER004 : "Sindrome metabolica"
HER005 : "Diabete mellito tipo 2"
HER006 : "Trombofilia ereditaria"
HER007 : "Ictus giovanile"
HER008 : "Aborti ricorrenti (trombofilia)"
HER009 : "Complicanze ostetriche (trombofilia)"
HER010 : "Alzheimer familiare precoce"
HER011 : "Demenza (Alzheimer, vascolare)"
HER012 : "Declino cognitivo lieve"
HER013 : "Tumore mammario ereditario (BRCA1/2)"
HER014 : "Tumore ovarico ereditario"
HER015 : "Tumore endometriale"
HER016 : "Tumore prostatico"
HER017 : "Tumore colorettale"
HER018 : "Sindrome di Lynch"
HER019 : "Poliposi adenomatosa familiare"
HER020 : "Depressione maggiore ricorrente"
HER021 : "Lupus eritematoso sistemico"
HER022 : "Psoriasi"
HER023 : "Malattie infiammatorie intestinali"
HER024 : "Cardiopatia ereditaria"
HER025 : "Morte cardiaca improvvisa in giovane età"
HER026 : "Eventi trombotici in sedi inusuali"
HER027 : "Cardiopatie (rischio aumenta con l’età)"
HER028 : "Ictus e TIA"
#HER029 : "Diabete tipo 2"
HER030 : "Tumore polmone"
HER031 : "Osteoporosi/fratture da fragilità"
HER032 : "Malattie neurodegenerative (es. Parkinson)"
HER033 : "Malattie cardiovascolari (esordio precoce più frequente negli uomini, ma maggiore mortalità nelle donne dopo la menopausa)"
HER034 : "Depressione (più prevalente nelle donne)"
HER035 : "Disturbo da abuso di sostanze"
HER036 : "Anemia falciforme"
HER037 : "Talasemia"
HER038 : "Ipensensibilità a farmaci (HLA-B1502/carbamazepina)"
HER039 : "Ipovitaminosi D/osteomalacia"
HER040 : "Disturbo post-traumatico da stress (PTSD)"
HER041 : "Depressione maggiore"
HER042 : "Disturbi d’ansia e panico"
HER043 : "Disturbi psicosomatici (colon irritabile, fibromialgia)"
HER044 : "Rischio suicidario aumentato"
HER045 : "Malattie cardiovascolari da stress cronico (sindrome di Takotsubo)"
HER046 : "Dismetabolismi (obesità, sindrome metabolica)"
HER047 : "Disfunzioni del sonno"
HER048 : "Compromissione immunitaria da stress cronico"
HER049 : "Artrite Reumatoide (AR)"
HER050 : "Tiroidite di Hashimoto (autoimmune)"
HER051 : "Tumori solidi (es. ovarico, colon-retto, prostata)"
HER052 : "Morbo di Addison autoimmune (insufficienza surrenalica primaria)"
HER053 : "Ictus ischemico acuto"
HER054 : "Depressione maggiore e sintomi da ansia grave"
HER055 : "Stress cronico con disregolazione dell’asse HPA"
HER056 : "Tumore epatico (epatocarcinoma)"
HER057 : "Disidratazione grave"
HER058 : "Prediabete"
HER059 : "Steatosi epatica non alcolica (NAFLD)"
HER060 : "Sindrome da attivazione macrofagica"
HER061 : "Pubertà precoce o ritardata"
HER062 : "Obesità cronica"
HER063 : "Iperplasia surrenalica congenita"
HER064 : "Ipogonadismo"
HER065 : "Infezioni croniche"
HER066 : "Anemia da infiammazione"
HER067 : "Colon irritabile post-infettivo"
HER068 : "Infertilità"
HER069 : "Ipoglicemia reattiva"
HER070 : "Trombocitopenia"
HER071 : "Trombocitosi"
HER072 : "Iperpotassiemia / Ipopotassiemia"
HER073 : "Nefropatia diabetica"
HER074 : "Ittero"
HER075 : "Ipertrigliceridemia"
HER076 : "Pancreatite cronica / Tumore pancreatico"
HER077 : "Iperinsulinemia"
HER078 : "Tiroidite subacuta/cronica"
HER079 : "Infezioni batteriche e virali acute o croniche"
HER080 : "Disfunzioni mitocondriali"
HER081 : "Colestasi"
HER082 : "Infezioni opportunistiche"
HER083 : "Glomerulonefrite"
HER084 : "Leucemia acuta e cronica"
HER085 : "Disturbi dell’umore e neuropsichiatrici"
HER086 : "Sindrome di Cushing"
HER087 : "Anemia (sideropenica, megaloblastica, emolitica)"
HER088 : "Ipertiroidismo"
HER089 : "Linfoma"
HER090 : "Disturbi cognitivi/dell’umore"
HER091 : "Acidosi metabolica"
HER092 : "Epatite"
HER093 : "Cancro"
HER094 : "Sindrome intestino irritabile"
HER095 : "Malattie metaboliche rare"
HER096 : "Mielodisplasie/mielofibrosi"
HER097 : "Infiammazioni sistemiche/localizzate"
HER098 : "Insufficienza renale"
HER099 : "Menopausa precoce"
HER100 : "Xantomatosi"
HER101 : "Malassorbimento/intolleranze"
HER102 : "Amenorrea/irregolarità mestruali"
HER103 : "Sindrome Nefrosica"
HER104 : "Deficit Vitamina A"
HER105 : "Deficit Vitamina B1 (Tiamina)"
HER106 : "Deficit Vitamina B2 (Riboflavina)"
HER107 : "Deficit Vitamina B3 (Niacina)"
HER108 : "Deficit Vitamina B6"
HER109 : "Deficit Vitamina B12"
HER110 : "Deficit Folati"
HER111 : "Deficit Vitamina C"
HER112 : "Deficit Vitamina E"
HER113 : "Deficit Vitamina K"
HER114 : "Disbiosi intestinale"
HER115 : "Chetoacidosi diabetica (DKA)"
HER116 : "Ipotiroidismo"
HER117 : "Insulino-resistenza"
HER118 : "Iperazotemia prerenale/postrenale"
HER119 : "Tiroidite subacuta (De Quervain)"
HER120 : "Cirrosi epatica"
HER121 : "Diabete tipo 1"
HER122 : "Sindrome di Gilbert"
HER123 : "ME/CFS (Sindrome da fatica cronica)"
HER124 : "Aterosclerosi subclinica"
HER125 : "Tumori ipofisari (PitNET)"
HER126 : "Ipercolesterolemia familiare"
HER127 : "Gozzo tossico multinodulare"
HER128 : "Adenoma tossico"