map:
  # ===== FUNZIONE TIROIDEA =====
  ipotiroidismo:
    feature: ipotiroidismo
    values:
      no: no
      primario: primario
      secondario: secondario
      non_so: non_so

  ipertiroidismo:
    feature: ipertiroidismo
    values:
      no: no
      attualmente_in_trattamento: attualmente_in_trattamento
      trattato_risolto: trattato_risolto
      non_trattato: non_trattato
      non_so: non_so

  nodulo_tiroide:
    feature: nodulo_tiroide
    values:
      no: no
      benigno: benigno
      sospetto: sospetto
      maligno: maligno
      non_so: non_so

  # ===== APPARATO RESPIRATORIO =====
  asma:
    feature: asma
    values:
      mai: mai
      diagnosticata_in_trattamento: diagnosticata_in_trattamento
      episodi_non_diagnosticati: episodi_non_diagnosticati
      passato_non_sintomatico: passato_non_sintomatico
      non_so: non_so

  farmaci_asma:
    feature: farmaci_asma
    values:
      si: si
      no: no

  sintomi_asma:
    feature: sintomi_asma
    values:
      si: si
      no: no

  spirometria_12_mesi:
    feature: spirometria_12_mesi
    values:
      si: si
      no: no

  bpco:
    feature: bpco
    values:
      nessuna_diagnosi: nessuna_diagnosi
      diagnosi_bpco: diagnosi_bpco
      sintomi_senza_diagnosi: sintomi_senza_diagnosi
      ex_fumatore_con_sintomi: ex_fumatore_con_sintomi
      non_so: non_so

  spirometria_bpco:
    feature: spirometria_bpco
    values:
      si: si
      no: no

  fumo_attuale:
    feature: fumo_attuale
    values:
      si: si
      no: no
      ex_fumatore: ex_fumatore

  difficolta_respiratorie_quotidiane:
    feature: difficolta_respiratorie_quotidiane
    values:
      si: si
      no: no

  polmonite:
    feature: polmonite
    values:
      mai: mai
      una_volta: una_volta
      piu_volte: piu_volte
      ricovero: ricovero
      non_ricordo: non_ricordo

  rischio_polmonite:
    feature: rischio_polmonite
    values:
      si: si
      no: no

  vaccino_pneumo_influ:
    feature: vaccino_pneumo_influ
    values:
      si_recentemente: si_recentemente
      si_passato: si_passato
      no: no
      non_so: non_so

  # ===== APPARATO GASTROINTESTINALE =====
  diarrea_3_mesi:
    feature: diarrea_3_mesi
    values:
      no: no
      episodio_acuto: episodio_acuto
      episodi_brevi: episodi_brevi
      diarrea_cronica: diarrea_cronica
      non_so: non_so

  sangue_feci:
    feature: sangue_feci
    values:
      si: si
      no: no

  perdita_peso:
    feature: perdita_peso
    values:
      si: si
      no: no

  associazione_diarrea:
    feature: associazione_diarrea
    values:
      si: si
      no: no

  esami_feci:
    feature: esami_feci
    values:
      coprocoltura: coprocoltura
      calprotectina: calprotectina
      test_celiachia: test_celiachia
      altro: altro

  altri_esami:
    feature: altri_esami
    passthrough: true

  # ===== MALATTIE INFETTIVE =====
  morbillo:
    feature: morbillo
    values:
      bambino_conferma_medico: bambino_conferma_medico
      non_certo: non_certo
      mai_avuto: mai_avuto
      non_ricordo: non_ricordo

  varicella:
    feature: varicella
    values:
      confermata_medico: confermata_medico
      non_sicuro: non_sicuro
      mai_avuta: mai_avuta
      non_ricordo: non_ricordo

  decorso_varicella:
    feature: decorso_varicella
    values:
      si: si
      no: no
      non_so: non_so

  scarlattina:
    feature: scarlattina
    values:
      diagnosticata_medico: diagnosticata_medico
      senza_conferma: senza_conferma
      mai_avuta: mai_avuta
      non_ricordo: non_ricordo

  decorso_scarlattina:
    feature: decorso_scarlattina
    values:
      si: si
      no: no
      non_so: non_so

  rosolia:
    feature: rosolia
    values:
      confermata_medico: confermata_medico
      senza_conferma: senza_conferma
      mai_avuta: mai_avuta
      non_ricordo: non_ricordo

  vaccino_test_rosolia:
    feature: vaccino_test_rosolia
    values:
      vaccinata: vaccinata
      test_immune: test_immune
      no_non_so: no_non_so

  pertosse:
    feature: pertosse
    values:
      diagnosticata_medico: diagnosticata_medico
      non_diagnosticata: non_diagnosticata
      no: no
      non_ricordo: non_ricordo

  difterite:
    feature: difterite
    values:
      confermata_diagnosi: confermata_diagnosi
      no: no
      non_ricordo: non_ricordo

  vaccino_difterite:
    feature: vaccino_difterite
    values:
      bambino: bambino
      richiami_adulto: richiami_adulto
      no: no
      non_ricordo: non_ricordo

  epatite_b_diagnosi:
    feature: epatite_b_diagnosi
    values:
      positivo_cronico: positivo_cronico
      risolto: risolto
      mai: mai
      non_so: non_so

  vaccino_epatite_b:
    feature: vaccino_epatite_b
    values:
      bambino: bambino
      adulto: adulto
      no: no
      non_so: non_so

  mononucleosi:
    feature: mononucleosi
    values:
      confermata: confermata
      non_confermata: non_confermata
      no: no
      non_so: non_so

  tubercolosi:
    feature: tubercolosi
    values:
      malattia_conclusa: malattia_conclusa
      test_positivo_senza_malattia: test_positivo_senza_malattia
      no: no
      non_so: non_so

  covid:
    feature: covid
    values:
      sintomi_lievi: sintomi_lievi
      sintomi_moderati_gravi: sintomi_moderati_gravi
      ricovero: ricovero
      terapia_intensiva: terapia_intensiva
      no: no
      non_sicuro: non_sicuro

  sequele_covid:
    feature: sequele_covid
    values:
      no: no
      risolte: risolte
      persistenti: persistenti
      non_so: non_so

  complicanze_covid_descrizione:
    feature: complicanze_covid_descrizione
    passthrough: true

  vaccino_covid:
    feature: vaccino_covid
    values:
      si: si
      no: no
      parziale: parziale
      non_so: non_so

  tipo_vaccino_covid:
    feature: tipo_vaccino_covid
    passthrough: true

  dosi_vaccino_covid:
    feature: dosi_vaccino_covid
    values:
      "1": "1"
      "2": "2"
      "3": "3"
      "4_plus": "4_plus"

  hiv_test:
    feature: hiv_test
    values:
      positivo: positivo
      negativo: negativo
      no: no

  terapia_antiretrovirale:
    feature: terapia_antiretrovirale
    values:
      regolare: regolare
      difficolta: difficolta
      non_iniziato: non_iniziato

  # ===== TRAUMI =====
  trauma_cranico:
    feature: trauma_cranico
    values:
      con_perdita: con_perdita
      senza_perdita: senza_perdita
      no: no
      non_ricordo: non_ricordo

  post_trauma_sintomi[]:
    feature: post_trauma_sintomi
    values:
      convulsioni: convulsioni
      disturbi_cognitivi: disturbi_cognitivi
      mal_di_testa: mal_di_testa

  fratture_traumi_ortopedici:
    feature: fratture_traumi_ortopedici
    values:
      con_intervento: con_intervento
      senza_intervento: senza_intervento
      no: no
      non_ricordo: non_ricordo

  aree_traumi:
    feature: aree_traumi
    passthrough: true

  trauma_toracico:
    feature: trauma_toracico
    values:
      con_complicanze: con_complicanze
      senza_complicanze: senza_complicanze
      no: no
      non_ricordo: non_ricordo

  trauma_addominale:
    feature: trauma_addominale
    values:
      con_lesioni: con_lesioni
      senza_lesioni: senza_lesioni
      no: no
      non_ricordo: non_ricordo

  # ===== CHIRURGIA =====
  appendicectomia:
    feature: appendicectomia
    values:
      si: si
      no: no
      non_ricordo: non_ricordo

  complicanze_appendicectomia:
    feature: complicanze_appendicectomia
    values:
      si: si
      no: no
      non_so: non_so

  tonsillectomia:
    feature: tonsillectomia
    values:
      si: si
      no: no
      non_ricordo: non_ricordo

  motivo_tonsillectomia:
    feature: motivo_tonsillectomia
    values:
      infezioni_ricorrenti: infezioni_ricorrenti
      apnee_russamento: apnee_russamento
      altro: altro
      non_ricordo: non_ricordo

  colecistectomia:
    feature: colecistectomia
    values:
      si: si
      no: no
      non_ricordo: non_ricordo

  motivo_colecistectomia:
    feature: motivo_colecistectomia
    values:
      coliche_calcoli: coliche_calcoli
      colecistite: colecistite
      altro: altro
      non_ricordo: non_ricordo

  ernia_inguinale:
    feature: ernia_inguinale
    values:
      si: si
      recidive: recidive
      dolori_occasionali: dolori_occasionali
      no: no
      non_ricordo: non_ricordo

  ernia:
    feature: ernia
    passthrough: true

  chirurgia_estetica:
    feature: chirurgia_estetica
    values:
      si_uno: si_uno
      si_piu_di_uno: si_piu_di_uno
      no: no

  prostatectomia:
    feature: prostatectomia
    values:
      no: no
      ipertrofia: ipertrofia
      tumore: tumore
      non_ricordo: non_ricordo

  complicanze_prostatectomia:
    feature: complicanze_prostatectomia
    values:
      nessuna: nessuna
      incontinenza: incontinenza
      disfunzione_erettile: disfunzione_erettile
      altri_disturbi: altri_disturbi

  # ===== PARAMETRI VITALI =====
  ipertensione:
    feature: ipertensione
    values:
      no: no
      occasionale: occasionale
      diagnosi: diagnosi
      non_so: non_so

  trattamento_ipertensione:
    feature: trattamento_ipertensione
    values:
      nessuno: nessuno
      farmaci: farmaci
      dieta: dieta
      entrambi: entrambi

  glicemia:
    feature: glicemia
    values:
      no: no
      occasionalmente: occasionalmente
      diagnosi: diagnosi
      non_so: non_so

  approccio_glicemia:
    feature: approccio_glicemia
    values:
      dieta: dieta
      esercizio: esercizio
      farmaci: farmaci
      insulina: insulina
      nessuno: nessuno
      accertamento: accertamento

  peso:
    feature: peso
    passthrough: true

  altezza:
    feature: altezza
    passthrough: true

  bmi:
    feature: bmi
    passthrough: true

  alterazioni_livelli_colesterolo:
    feature: alterazioni_livelli_colesterolo
    values:
      mai: mai
      passato_controllo: passato_controllo
      attuali: attuali
      in_trattamento: in_trattamento
      non_so: non_so

  valori_colesterolo:
    feature: valori_colesterolo
    passthrough: true

  valore_bap_test:
    feature: valore_bap_test
    passthrough: true

  valore_droms_test:
    feature: valore_droms_test
    passthrough: true

  # ===== ALLERGIE E FARMACI =====
  allergie[]:
    feature: allergie
    values:
      no: no
      farmaci: farmaci
      alimenti: alimenti
      ambientali: ambientali
      insetti: insetti
      altre: altre
      non_sicuro: non_sicuro

  allergie_altre:
    feature: allergie_altre
    passthrough: true

  farmaci_regolari:
    feature: farmaci_regolari
    values:
      no: no
      patologia_cronica: patologia_cronica
      terapia_ormonale: terapia_ormonale
      integratori: integratori

  farmaci_specifica:
    feature: farmaci_specifica
    passthrough: true

  stato_generale_influenzato_da_infiammazioni_o_infezioni:
    feature: stato_generale_influenzato_da_infiammazioni_o_infezioni
    values:
      frequentemente: frequentemente
      qualche_volta: qualche_volta
      raramente: raramente
      mai: mai